Update issue templates
CMSgov/eAPD pull request #2623
Opened 2020-10-30 14:13 UTC by jeromeleecms

These are the proposed templates from the team created back in August. Feel free to re-review and modify as needed.

2020-10-30 14:35 UTC, cthulhuplus requested changes
If you could remove the test template I created as a part of this I would be appreciative.

2020-10-30 16:32 UTC, jeromeleecms commented
@cthulhuplus As requested, the file has been removed from the branch.

2020-10-30 18:59 UTC, cthulhuplus approved these changes

2020-10-30 19:01 UTC, thetif approved these changes

2020-11-02 21:15 UTC, beparticular approved these changes

2020-11-02 21:17 UTC, merged