Tbolt/2736 program summary updates
CMSgov/eAPD pull request #2790
Opened 2021-01-19 20:57 UTC by tbolt

Resolves #2736 

### This pull request changes...

- Several updates to summary page (now titled APD Overview)

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2021-01-19 21:01 UTC, thetif approved these changes

2021-01-19 21:29 UTC, beparticular requested changes
The help text in the paragraph under Introduction needs to be updated:

The paragraph of help text for the Introduction field was changed to the follow to only show one instance of "future vision". 

Provide a brief introduction to the state program. Include context for this funding request by providing information such as current size of the program and how the program is positioned within the state. You might also include a high-level look at the history and context of the program and the state’s future vision for it.

2021-01-20 16:34 UTC, jeromeleecms approved these changes
Looks good.

2021-01-20 17:57 UTC, beparticular approved these changes

2021-01-20 20:35 UTC, merged