Hard Coding AMI to Golden Image for testing
CMSgov/eAPD pull request #2805
Opened 2021-01-26 15:14 UTC by cthulhuplus

Changes to Previews deploys to use the Golden AMI.

### This pull request changes...

- Uses latest golden image
- expected change 2

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2021-01-27 21:15 UTC, cthulhuplus commented
I was able to log in to the app, but the OS that the app is built upon is different, so I'd like everyone to really have at this preview to make sure there aren't undiscovered flaws before we merge this change in.

2021-01-27 21:39 UTC, beparticular commented
@cthulhuplus are there any anticipated flaws, or major areas of concern? i'm not seeing anything yet, but want to make sure I'm looking in the right places.

2021-01-27 21:49 UTC, cthulhuplus commented
> @cthulhuplus are there any anticipated flaws, or major areas of concern? i'm not seeing anything yet, but want to make sure I'm looking in the right places.

@beparticular I am hoping that I caught everything. I invited everyone to review it because I want every one to poke at it in their own way. So, just use it how you would and if you find anything let me know. Hopefully you wont!

2021-01-28 14:59 UTC, thetif approved these changes
looks good from what I understand about these aws scripts

2021-01-28 15:51 UTC, beparticular approved these changes

2021-01-28 21:13 UTC, radavis requested changes
Looks good other than containing some commented code.

https://kentcdodds.com/blog/please-dont-commit-commented-out-code

2021-01-28 21:13 UTC, radavis commented on bin/preview-deploy/aws.user-data.sh
> +#service nginx restart
Delete this line.

2021-01-28 21:13 UTC, radavis commented on bin/preview-deploy/aws.user-data.sh
> +#amazon-linux-extras install nginx1.12
Delete this line.

2021-02-02 15:54 UTC, tbolt reviewed
Seems OK to me. Is there something specific I can test?

2021-02-03 18:45 UTC, cthulhuplus commented
This PR is no longer relevant, the changes have been merged in as a part of other work and is being left open to provide a safe place for the new team members to explore.

2021-02-25 16:02 UTC, closed without merging