persist okta user data
CMSgov/eAPD pull request #2838
Opened 2021-02-03 17:36 UTC by radavis

Describe the pull request here, including any supplemental information needed to understand it.

### This pull request changes...

- expected change 1
- expected change 2

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

2021-02-12 17:39 UTC, thetif approved these changes

2021-02-12 17:39 UTC, thetif commented on bin/preview-deploy/aws.sh
> +    --key-name radavis \
are you still testing this?

2021-02-12 18:33 UTC, radavis commented on bin/preview-deploy/aws.sh
> +    --key-name radavis \
Resolved

2021-02-16 17:46 UTC, tbolt approved these changes
Looks good

2021-02-16 18:00 UTC, beparticular requested changes
Apologies again for not catching this sooner - can the text be changed to: 

Contact the State Administrator for more information.

2021-02-16 19:26 UTC, beparticular approved these changes

2021-02-23 21:33 UTC, eStar386 reviewed
There is an accessibility and bug that prevents the screen from redirecting the user to the login screen this is fixed with a larger pr #2891

2021-02-23 21:39 UTC, eStar386 commented
This functionality has accessibility issues (wave) and a bug that prohibits it from redirecting to the pending deliveries screen and is within #2838
Test Script is located at [2771 ](https://drive.google.com/file/d/1HFm8OB6jDnFjKF4jvbbUIXcz-56P64Wn/view?usp=sharing)

2021-02-24 14:22 UTC, eStar386 commented
During backend validation, an issue was discovered with the database saving user information. Update the test steps above to assist with the investigation.

2021-02-24 15:22 UTC, eStar386 commented
@radavis - This restates the bug more eloquently. It mirrors the above comment.
Type of Bug Title: Backend Validation Failure 

Role Affected: em@il.com

Description of issue: During backend validation, an issue was discovered with the database saving new user pending deliveries. The new user state affiliation must be sent to the em@il user account whenever the default case of Alaska is used. 

Expected Result:  New user added with a state affiliation of Alaska.  The New user requests received and appears on the state admin dashboard. 

Actual Result: The new user has a state affiliation of Alaska with the pending deliveries request. However, the em@il user doesn’t have the request in the dashboard.


Steps to Reproduce 

•	Create an Okta User: https://test.reg.idm.cms.gov/registration.html?appid=eapd
•	Login
•	Select 'Alaska'
•	Verify that 'State Administrator' link is present with href='mailto:...'
•	Login into the em@il.com account and verify the new user(s) requested for Alaska is in pending deliveries.

2021-03-02 17:04 UTC, radavis commented
@eStar386 I was able to confirm this issue.

Requests from the front-end when viewing the `/state-admin` path were returning `502 Bad Gateway` responses. Thus, no information was being retrieved from the back-end.

Merging changes from master seem to have corrected this problem. Please re-test when you have the time. Thank you.

2021-03-10 13:36 UTC, eStar386 commented
Retested and this resolves the bug.

2021-03-10 13:38 UTC, eStar386 approved these changes

2021-03-10 22:57 UTC, jeromeleecms reviewed
The scope of the PR does not reflect the scope of the actual issue. We should also have this same functionality for the "Denied Dashboard" as well:

![image](https://user-images.githubusercontent.com/34279968/110709251-c8525c00-81b0-11eb-8757-6688679f7a53.png)

Currently the text does not link to anything. If we do change the scope of this issue, let's change the title to include all dashboards -- or I'm OK with switching it to a separate issue to resolve. @thetif

2021-03-24 19:15 UTC, thetif requested changes

2021-03-24 20:15 UTC, knollfear commented on bin/preview-deploy/aws.sh
>      | jq -r -c '.Instances[0].InstanceId'
sure.  I have no idea why this is part of the MR, I didn't look at this part.

2021-03-25 13:22 UTC, tbolt approved these changes
Nice work

2021-03-25 15:10 UTC, thetif approved these changes

2021-03-30 18:53 UTC, NAretakis approved these changes
I see the admin email, clicking it works too!! Good to go!

2021-04-01 18:25 UTC, eStar386 approved these changes
Passed - the denied and revoked panels are added. Testing information above.

2021-04-05 13:11 UTC, merged