Tbolt/2582 Allow additional affiliation requests
CMSgov/eAPD pull request #3144
Opened 2021-05-21 18:54 UTC by tbolt

Resolves #2582 

**Description-**
This introduces a new page "Manage Account" that can be accessed from the top right nav. On this page the users existing affiliations are listed (currently ALL of them including requests/revoked/denied, we will likely update this). This page also allows a user to request access to additional states.

**This pull request changes...**

- Adds "Manage Account" link to top right navigation
- Allows viewing of existing affiliations
- Allows requesting additional affiliations

**Steps to manually verify this change...**

1. Login to the application with `norole` test account. Request access to 2x states.
2. Navigate to "Manage Account" via newly added "Manage Account" link in the nav
3. Verify the 2x states previously requested appear under Current Affiliations
4. Add a new state to be requested
5. Submit request
6. Should see the "Thank You" message

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2021-05-24 18:33 UTC, knollfear commented on web/src/containers/admin/ManageAccount.js
> +      {showConfirmation && <StateAccessRequestConfirmation action={handleCompleteAccessRequest} />}
would a ternary operator be more clear here?

showConfirmation ?
 <StateAccessRequestConfirmation ....>
: 
 
<StateAccessRequest ...>

2021-05-24 18:44 UTC, tbolt commented on web/src/containers/StateAccessRequest.js
> +    const stateDetails = STATES.find(item => item.id === element.state_id)
Yea, not a bad idea. I was re-using `/utils/states` which already existed and is used in other places. You think re-factoring it and updating it wherever it's used is a good option?

2021-05-24 18:45 UTC, tbolt commented on web/src/containers/StateAccessRequest.js
> +    return { id: element.state_id, name: stateDetails.name, disabled: true }
nope, good catch

2021-05-24 19:26 UTC, knollfear commented on web/src/containers/StateAccessRequest.js
> +    const stateDetails = STATES.find(item => item.id === element.state_id)
maybe just create a second "STATEMAP" that is in that format would be easiest

2021-05-25 13:56 UTC, knollfear approved these changes
LGTM.  Nice work.

2021-05-27 14:18 UTC, eStar386 commented
Documented Functional Issue with the sorted list: When testing the ability to add states and eliminating selected states (seen in the current affiliations portion) from the sorted list. The list of states is returned to the user unsorted.
<img width="1440" alt="unsorted List " src="https://user-images.githubusercontent.com/71447081/119842396-a2497780-bed4-11eb-98e6-c6e7284520c1.png">

2021-05-27 18:56 UTC, eStar386 commented
Failed the accessibility testing for the confirmation page.

2021-05-27 19:05 UTC, eStar386 requested changes
This is ready for review once the confirmation page passes the wave. Passes functional and accessibility tests.

2021-05-27 20:47 UTC, eStar386 approved these changes
![image (3)](https://user-images.githubusercontent.com/71447081/119894680-e7889c00-bf0a-11eb-80d8-7a722708f241.png)

Per a conversation with @tbolt there is a problem with the build and not with the actual confirmation page. The screenshot above was provided by Ty.

2021-05-27 21:13 UTC, eStar386 commented
Passes functional requirements of allowing a user to select multi-state affiliations and noted that the accessibility failures were due to a build issue.

2021-05-28 13:12 UTC, tbolt commented
@eStar386 I did end up seeing that issue. I have since made an update to resolve it. Please verify you are not seeing it anymore. Thanks

2021-05-28 14:48 UTC, eStar386 approved these changes
Per the request of @tbolt , I reviewed the committed changes. Confirming it passes functional and accessible checks.  
<img width="1440" alt="Screen Shot 2021-05-28 at 10 28 05 AM" src="https://user-images.githubusercontent.com/71447081/120001806-29185600-bfa2-11eb-8b82-2f15bce9103f.png">

2021-05-28 15:51 UTC, beparticular approved these changes

2021-06-07 15:57 UTC, NAretakis approved these changes
Good to go!

2021-06-07 19:09 UTC, merged