dmirano/3282 apd overview cypress test
CMSgov/eAPD pull request #3307
Opened 2021-07-22 13:43 UTC by mirano-darren

resolves #3282

**Description-**
Cypress test for filling out the APD overview section. 

**This pull request changes...**

- adds cypress dependencies in the web directory

**This pull request also touches…**

- hopefully nothing other than the web directory

**This pull request was tested in the follow ways…**

- tested off a fresh checkout (wasn't too sure what to put here)

**Steps to manually verify this change...**

1. rerun npm install in /web/ and /api/
2. build docker containers
3. run eAPD app as normal
3. launch cypress in the /web/ directory with "npx cypress open"
4. click on the test "apd-overview.spec.js"
5. cypress should automatically open and run the tests
6. all three tests should pass

### This pull request is ready to review when...

- [X] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [X] Code has been reviewed by someone other than the original author
- [X] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2021-07-27 17:19 UTC, thetif approved these changes
Great job! Just a couple of suggestions of things that you could refactor.

2021-07-27 17:19 UTC, thetif commented on web/cypress/integration/apd-tests/apd-overview.spec.js
> +    cy.then(() => {
```
cy.get("[class='ds-c-choice']").each(($el, index, list) => {
    years.push(list[index].value);
    if (!list[index].checked) {
      cy.findByRole('checkbox', { name: list[index].value }).check({
        force: true
      });

      cy.contains('Saving').should('exist');
      cy.contains('Saved').should('exist');
    }
  });
  cy.then(() => {
    cy.get('[class="ds-h1 apd--title"]').should('contain', years[0]);
    cy.get('[class="ds-h1 apd--title"]').should(
      'contain',
      years[years.length - 1]
    );
  });
```

2021-07-27 20:40 UTC, thetif requested changes

2021-07-27 20:40 UTC, thetif commented on web/cypress/integration/apd/01-apd-overview.spec.js
> +    cy.get("[class='ds-c-choice']").each(($el, index, list) => {
try doing this and the next loop as one loop
```
cy.get("[class='ds-c-choice']").each(($el, index, list) => {
    years.push(list[index].value);
    if (!list[index].checked) {
      cy.findByRole('checkbox', { name: list[index].value }).check({
        force: true
      });

      cy.contains('Saving').should('exist');
      cy.contains('Saved').should('exist');
    }
  });
  cy.then(() => {
    cy.get('[class="ds-h1 apd--title"]').should('contain', years[0]);
    cy.get('[class="ds-h1 apd--title"]').should(
      'contain',
      years[years.length - 1]
    );
  });
  ```

2021-07-27 20:40 UTC, thetif commented on web/cypress/integration/apd/apd-activities/activities.spec.js
> +/// <reference types="cypress" />
can you remove this file from this branch and just work on it in your new branch?

2021-07-28 13:03 UTC, tbolt approved these changes
Nice work!

2021-07-28 16:43 UTC, thetif commented
I'm getting one test failure, can you check it out?
![Screen Shot 2021-07-28 at 12 43 00 PM](https://user-images.githubusercontent.com/62778/127362791-40ecebd5-150a-42e0-81ca-2b694220d141.png)

2021-07-28 18:48 UTC, thetif approved these changes

2021-07-28 18:48 UTC, thetif commented
all tests passing, good to merge 

![Screen Shot 2021-07-28 at 2 47 48 PM](https://user-images.githubusercontent.com/62778/127379109-81f28b8a-b8e7-4550-8247-f97db829e83c.png)

2021-07-29 12:08 UTC, merged