Added title case to various heading, titles, etc...
CMSgov/eAPD pull request #3359
Opened 2021-08-02 19:27 UTC by mirano-darren

resolves #2438 

**Description-**
Added title case to various titles, labels, headings, etc...

**This pull request changes...**

- web/src/components/Instructions.js
- web/src/components/Section.js
- web/src/containers/ApdStateProfileMedicaidOffice.js
- web/src/containers/AssurancesAndCompliances.js
- web/src/containers/ExecutiveSummaryBudget.js
- web/src/containers/PreviousActivities
- web/src/containers/activity/CostAllocateFFP.js
- web/src/containers/activity/CostAllocateFFPQuarterly.js
- web/src/containers/activity/Costs.js
- web/src/containers/activity/EntryDetails.js
- web/src/containers/activity/CostAllocation/OtherFunding.js
- web/src/containers/ApdKeyPerson/ApdKeyPersonForm.js
- web/src/containers/viewOnly/AssurancesAndCompliances.js
- web/src/containers/viewOnly/ExecutiveSummary.js
- web/src/reducers/nav.items.js
- web/src/components/ContinuePreviewButtons.js

**This pull request also touches…**
- web/package.json
- web/package-lock.json

**possible side effects of this change**
 - Could crash the website if titleCase() was called wrong, but I made sure this wasn't the case before creating this PR

**This pull request was tested in the follow ways…**
- Going to each page on the website and making sure it doesn't crash

**Steps to manually verify this change...**

1. See if everything desired is title cased correctly

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [x] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [x] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [x] Design has approved the experience
- [ ] Product has approved the experience

2021-08-03 12:45 UTC, thetif requested changes

2021-08-03 12:45 UTC, thetif commented on web/src/components/Instruction.js
> +  const heading = t([source, titleCase('heading')], { defaultValue: false, ...args });
you need to put titleCase around the t() function

2021-08-03 12:45 UTC, thetif commented on web/src/components/Section.js
> +  const title = t([resource, titleCase('title')], { defaultValue: false });
you need to put titleCase around the t() function

2021-08-05 18:36 UTC, thetif approved these changes
Looks good!

2021-08-05 18:37 UTC, thetif commented
Sorry @mirano-darren I pulled this down to look at the package-lock file and then ended up pulling Bill's branch in here by mistake and then I couldn't roll it back 🤦. I got it back to how you had it but I lost your git commit history. You still get full credit for this one though!

2021-08-05 18:40 UTC, mirano-darren commented
> Sorry @mirano-darren I pulled this down to look at the package-lock file and then ended up pulling Bill's branch in here by mistake and then I couldn't roll it back 🤦. I got it back to how you had it but I lost your git commit history. You still get full credit for this one though!

All good! :D

2021-08-12 23:17 UTC, beparticular commented
@mirano-darren @thetif I can see where most of these have been updated. Some I'm not sure, they appear to be title case already in staging. 

One thing I did want to check on, in Assurances and Compliances a couple of the links appear to be missing in this test environment. Can you take a look and see if that's related to something else, or if something happened there? Thanks!

2021-08-20 14:52 UTC, beparticular commented
@mirano-darren @thetif 
This is looking good, I can see where most of the changes are. 

There are still some items in the executive summary that look like they should be title case. 
Total cost: 
Start date - End date: Date not specified - Date not specified
Total cost of activity:
Total funding request:  

Those look like they could be the same style as the summaries on Private Contractor Cost or Outcomes and Metrics?

2021-09-08 20:08 UTC, beparticular approved these changes

2021-09-13 18:39 UTC, merged