Tforkner/3499 private contractor costs validation
CMSgov/eAPD pull request #3895
Opened 2022-03-25 14:45 UTC by thetif

Resolves #3499 

**Description-**
Added validation to the private contractor form.

**This pull request changes...**

- private contractor form will not save unless the form is valid

**This pull request also touches…**

- adds in testing-library linting

### This pull request is ready to review when...

- [x] Automated tests are updated (and all tests are passing)
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2022-04-04 18:55 UTC, tbolt approved these changes
Looks great. Nice cleanup to the tests with testing-library

2022-04-07 20:01 UTC, itsonlydio commented
| Given  | When | Then| Result |
| ------------- | ------------- | ------------- | ------------- |
| Date field Month/Day | When I entered an invalid date and then a valid date  | the new VALID date should be accepted and save the form  | failed |

This is good the only thing we found is the 'Provide Start Date' warning still appears. 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/102550082/162286176-7cf6f71e-8a1b-4751-9e46-09b0080545db.png">

2022-04-07 20:09 UTC, mirano-darren commented
Also the contractor view in the dashboard doesn't match Figma for me? Here's what I'm seeing
![image](https://user-images.githubusercontent.com/87026092/162287435-2d72e1cf-03ed-46a8-a1a0-f8ff54d7a1ef.png)

The Figma has a line separating the two
![image](https://user-images.githubusercontent.com/87026092/162287518-3ce0a592-8d83-405f-8f13-e24a2a171ca7.png)

2022-04-08 21:14 UTC, thetif commented
@itsonlydio and @mirano-darren I think I addressed the issues can you check it again?

2022-04-14 19:42 UTC, mirano-darren commented
Update on some of the test cases found:
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| A date field  | An invalid month is entered then corrected to a valid month | The newly entered month should be considered valid, with no error message appearing  |  PASS ✔️, but then you cannot save afterwards! FAIL ❌  |
| Private contractor dashboard view  | Multiple contractors have been entered  | A line is separating the contractors | PASS ✔️ |
| A date field  | An invalid day is entered then corrected to a valid day | The newly entered day  should be considered valid, with no error message appearing  |  PASS ✔️, but you cannot save afterwards! FAIL ❌  |
| A date field  | a number greater than 12 is entered for the month  | Save button isn't clickable, | PASS ✔️ |
| A date field  | a number greater than 32 is entered for the day | Save button isn't clickable | PASS ✔️ |
| Both date fields | The end date comes before the start date  | Save button is clickable, no error message appears | FAIL ❌ |
| A date field | When you enter a date for the first time | Whether or not the date is valid, the inline validation error message appears. Retriggering the validation will then accept a valid date | FAIL ❌

2022-04-19 21:03 UTC, thetif commented
@mirano-darren can you test this again when you get the chance? I think I got it all fixed this time.

2022-04-21 17:30 UTC, jeromeleecms requested changes
The date validation on this field doesn't seem be working (this is seen as valid):

![image](https://user-images.githubusercontent.com/34279968/164512630-308dc0ce-44ea-4fde-9265-5eb5cf9d6d4d.png)

Also, saving the form truncates the values to the proper MM-DD-YYYY. I don't know if it's related or not, but the preview site crashed right after...

Number of hours - this should allow 0 hours (consistent with the language in the validation). In some cases, a state may have 0 cost for the first year, but have a cost the 2nd year (or vice versa)

![image](https://user-images.githubusercontent.com/34279968/164512798-5a484d6a-b9ec-49d4-8e95-f2f31c9e1aa8.png)

FFY Cost should also allow 0 for the same rationale. In this case, the validation should read "Provide an annual cost greater than or equal to 0"

![image](https://user-images.githubusercontent.com/34279968/164516766-59fb6424-709f-4f2f-a072-876856392ae5.png)

2022-04-22 14:36 UTC, thetif commented
@jeromeleecms I'm still working allowing 0 on those number, but the problem with the date is that the design system date field truncates the numbers so even though you are entering 111 in month, it's only returning 11 to us, so that looks correct.

2022-04-22 15:49 UTC, jeromeleecms commented
Can/should we add a "maxlength" tag to the date fields? I vaguely remember they introduced that in HTML5 (seems like there is a react equivalent of "maxLength") or does the design system not want us using that or does that cause other problems?

2022-04-22 17:42 UTC, thetif commented
we don't have access to those fields, the best we could do is put in a ticket with design system

2022-04-22 17:43 UTC, thetif commented
also, we previously didn't allow 0s in any number fields, but I've opened it up so that we can use 0

2022-04-22 20:22 UTC, beparticular approved these changes

2022-04-29 13:50 UTC, tbolt approved these changes

2022-04-29 14:21 UTC, tbolt approved these changes
looks good. nice work

2022-04-29 14:21 UTC, tbolt commented on web/src/components/DateField.js
> +            yearInvalid: !isNumeric(year) || +year < 1900 || +year > 2100
this is nice!

2022-05-02 16:31 UTC, itsonlydio reviewed
As I was testing the in-line validation works in the date fields, Contract costs, hourly resource fields and FFY Cost FIeld.
<img width="799" alt="Screen Shot 2022-05-02 at 12 24 46 PM" src="https://user-images.githubusercontent.com/102550082/166276140-84b36226-99ff-41f8-899d-1bc1e0ad3292.png">
<img width="784" alt="Screen Shot 2022-05-02 at 12 24 54 PM" src="https://user-images.githubusercontent.com/102550082/166276146-a2f526a0-e006-4254-9645-53b7867bbc3a.png">
<img width="680" alt="Screen Shot 2022-05-02 at 12 25 06 PM" src="https://user-images.githubusercontent.com/102550082/166276152-38a3a598-4bcd-4622-8637-e2f7de963f1a.png">

2022-05-02 21:42 UTC, jeromeleecms approved these changes
Looks good!

2022-05-03 21:54 UTC, merged