Dmirano/3784 executive summary restructure
CMSgov/eAPD pull request #3912
Opened 2022-03-29 19:27 UTC by mirano-darren

Resolves #3784 

**Description-**
executive summary refactor

**This pull request changes...**

- file locations of requested filed and affected tests

**This pull request was tested in the follow ways…**

- npm test in /web/ passes
- app boots up normally

**Steps to manually verify this change...**

1. verify all requested files were moved to the right location

### This pull request is ready to review when...

- [x] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [x] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2022-03-29 20:19 UTC, mirano-darren commented
merge conflicts will be solved once key state refactor is in (#3901)

2022-04-01 13:48 UTC, tbolt approved these changes

2022-04-05 22:25 UTC, thetif requested changes
one file needs to be changed

2022-04-05 22:25 UTC, thetif commented on web/src/pages/apd/ApdReadOnly.js
> +import ExecutiveSummary from './executive-summary/ExecutiveSummary';
I think this should be ExecutiveSummaryReadOnly

2022-04-06 18:09 UTC, thetif approved these changes

2022-04-06 19:37 UTC, merged