Tbolt/3498 Other state expenses validation
CMSgov/eAPD pull request #3957
Opened 2022-04-08 12:15 UTC by tbolt

Resolves #3498 

**Description-**
* Updates other state expenses section to use new form validation tools

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2022-04-21 19:14 UTC, thetif approved these changes

2022-04-21 19:14 UTC, thetif commented on integrationTests/cypress/integration/02-apd/01-apd-basics.spec.js
> +
lots of empty space

2022-04-21 19:14 UTC, thetif commented on integrationTests/cypress/page-objects/activities-state-staff-expenses-page.js
> +  fillExpense = (years, expenseIndex, category, costs, desc) => {
should probably switch this to an object so it's easier to call

2022-05-05 18:19 UTC, mirano-darren commented
Well done!
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| other state expenses subform | form is filled out with valid fields | save button is clickable and saves | PASS ✅ |
| other state expenses subform | right after pressing "Add State Expense" and no fields are touched | save button is disabled | PASS ✅ |
| other state expenses subform | tab navigating through the form, not filling anything out | validation error appears on all fields | PASS ✅ |
| an existing other state expenses subform | form is edited, click cancel | changes are not saved  | PASS ✅ |
| an existing other state expenses subform | form is edited, click save| changes are saved  | PASS ✅ |
| an existing other state expenses subform | a field is edited to be invalid | inline validation triggers and save button is disabled| PASS ✅ |

2022-05-05 18:19 UTC, mirano-darren approved these changes

2022-05-12 16:42 UTC, jeromeleecms approved these changes
Besides the system wide bug on subforms filed for #4047, this works as advertised. Gtg from my end.

2022-05-16 14:35 UTC, beparticular requested changes
Steps: Expected: 
Don't select an expense category
Fill in all the other fields, can't save ofc
Go back to the expense category and select an option
Unexpected: the validation error is still there after I've chosen an option. 

If I tab or click out of the field it updates and there is no longer an error, but the expected behavior would be that selecting an option would fix the problem and the error, rather than selecting an option and needing to navigate to another field.

2022-05-17 01:34 UTC, tbolt commented
@beparticular My understanding was that the team decided to only trigger validation "onBlur." Which means that even though you select an item from the dropdown you still have the field "focused" and only when you exit (tab or mouse click away from it) that would trigger the validation. We can revisit and make the call to have some exceptions because I agree the current behavior doesn't feel expected. We could switch to doing validation anytime a change is made for all inputs/fields. This would fix the issue you pointed out but also impact all other inputs. So for text inputs, as soon as you typed one character we would validate.

2022-05-17 20:43 UTC, beparticular approved these changes

2022-05-18 02:20 UTC, itsonlydio reviewed
The Other state expenses field validations works!

2022-05-18 10:59 UTC, merged