Tbolt/3449 Updates to default messages for empty fields in export view
CMSgov/eAPD pull request #4000
Opened 2022-04-22 14:16 UTC by tbolt

Resolves #3449 

**Description-**
This PR updates or adds the default messages for when fields are empty in the export view. See original ticket for specifics.

**Steps to manually verify this change...**

1. Login to view/export a APD
2. Compare the 3449 ticket language with new update messages

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

2022-05-12 15:31 UTC, thetif approved these changes
looks good, one nit-picky grammar thing

2022-05-12 15:31 UTC, thetif commented on web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
> +      {activity.outcomes.length === 0 && 'No outcome(s) and corresponding metrics were provided.'}
shouldn't this be
```
No outcome(s) or corresponding metrics...
```

2022-05-12 17:52 UTC, jeromeleecms requested changes
Outcome with no metric doesn't show the language "No metrics were specified for this outcome."

![image](https://user-images.githubusercontent.com/34279968/168137125-d0257f44-fa34-4271-a824-34a31c73e0a2.png)

Also, Per @thetif comments, I would be OK with updating this language:

"No outcome(s) and corresponding metrics were provided."

to 

"No outcome(s) and/or corresponding metric(s) were provided."

2022-05-16 12:28 UTC, tbolt commented
@jeromeleecms Good catch, that might have been reverted in the merge. I will update the language as well.

2022-05-16 14:30 UTC, beparticular approved these changes
The only comment I had was also what Jerome and Tif have fixed. Approved

2022-05-16 19:06 UTC, tbolt commented
@jeromeleecms Thanks, take a look now it should all be working

2022-05-17 11:38 UTC, tbolt commented
@jeromeleecms ok _now_ it should be working. I just tested the preview build and it was updated and working but let me know if you run into any other issues.

2022-05-17 13:55 UTC, mirano-darren commented
Nice work!
One question, and I guess this one is more for #3345, but where is the description for Budget and FFP come from? As of now it's just a blank section if it's default:
![image](https://user-images.githubusercontent.com/87026092/168825310-dd47e3f9-203e-4534-a4a6-5ae6b6ca1e45.png)
The ticket says to have the default message as `No response was provided for the Budget and FFP`. However there is no text boxes on the Budget and FFP page?

2022-05-17 16:48 UTC, mirano-darren approved these changes
😄

2022-05-18 02:13 UTC, itsonlydio reviewed
Looks good to me!

2022-05-18 10:26 UTC, merged